all:
	g++ cpp01.cpp -ocpp01.exe
	g++ cpp02.cpp -ocpp02.exe
	g++ cpp03.cpp -ocpp03.exe
	g++ cpp04.cpp -ocpp04.exe
	g++ cpp05.cpp -ocpp05.exe
	g++ cpp06.cpp -ocpp06.exe
	g++ cpp07.cpp -ocpp07.exe
	g++ cpp08.cpp -ocpp08.exe
	g++ cpp09.cpp -ocpp09.exe
	g++ cpp10.cpp -ocpp10.exe
	g++ cpp11.cpp -ocpp11.exe
	g++ cpp12.cpp -ocpp12.exe
	g++ cpp13.cpp -ocpp13.exe
	g++ cpp14.cpp -ocpp14.exe

	g++ u_link.cpp -o u_link.exe
	g++ u_ref.cpp -o u_ref.exe

clean:
	rm *.exe
